### ISSUE TITLE
Discuss and implement mission statement

### ISSUE THREAD

**Issue by tsal** [movement-engineer/foundation#5]

**Comment by tsal** [comment]
The bread starter (heh): " foundation built on principles of progress and social justice"

**Comment by ljpolaris** [comment]
*Mission Statement:*

We are a foundation built on principles of social justice starting at the
grassroots level. Having an online presence is essential for growth and
progress. We aim to help groups and organizations by providing options for
establishing such.

*Vision Statement:*

We hope to create safe spaces where grassroots movements can spread their
message and grow their support bases. By doing so, new and smaller groups
and organizations can avoid expenses of web design and use fundraising for
expenses more directly related to their social justice goals.

*Core Values:*

We believe that progress begins at the grassroots level.

We believe that having an online presence is vital to progress and that
those seeking social change should have access to this.

We believe that oppression is intersectional and we must work together to
combat this on a multifaceted front.

We believe in non-violent efforts to enact change.




__________________________________________

*“*Be good and you will be lonesome."
- Mark Twain

**Comment by tsal** [comment]
closed by #8
